name: fl_be_shared_example
description: Demonstrates how to use the fl_be_shared plugin.
publish_to: 'none'
version: 0.0.1
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_be_shared:
    path: ../
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true