name: fl_be_shared
description: Make your app appear in someone else's share list and get the parameters to share it
version: 0.0.1
repository: https://github.com/Wayaer/fl_be_shared.git

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: fl.be.shared
        pluginClass: FlBeSharedPlugin
      ios:
        pluginClass: FlBeSharedPlugin